### ISSUE TITLE
USER STORY: View Menu

### ISSUE THREAD

**Issue by atchutchi** [atchutchi/gamela-cake#7]
As a **customer** I can **view a cake menu** so that **informed decisions about product selection are made.**

## Acceptance Criteria

- The menu must list all cakes with images, descriptions, and prices.
- The menu must be accessible to all users, registered or not.
- The menu must be updated in real-time to reflect any changes in cake availability or prices.

## Tasks

- [x] Design a layout for the cake menu.
- [x] Implement a system to retrieve and display real-time data for cakes.
- [x] Ensure the menu is accessible and navigable for all users.
